make-dist: give priority to python3 over python2.7
python2.7 is deprecated and will no longer be supported starting
January 1, 2020.

Signed-off-by: Nathan Cutler <ncutler@suse.com>

diff --git a/make-dist b/make-dist
--- a/make-dist
+++ b/make-dist
@@ -61,6 +61,20 @@ download_boost() {
     rm -rf src/boost
 }
 
+_python_autoselect() {
+  python_command=
+  for interpreter in python3 python2.7 ; do
+    type $interpreter > /dev/null 2>&1 || continue
+    python_command=$interpreter
+    break
+  done
+  if [ -z "$python_command" ] ; then
+    echo "Could not find a suitable python interpreter! Bailing out."
+    exit 1
+  fi
+  echo $python_command
+}
+
 build_dashboard_frontend() {
   CURR_DIR=`pwd`
   TEMP_DIR=`mktemp -d`
